services:
  app:
    container_name: vaporfume-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/sqlite.db
      # Adicione outras vari√°veis de ambiente aqui ou use env_file
    volumes:
      - ./sqlite.db:/app/sqlite.db
      - ./public/uploads:/app/public/uploads
    # healthcheck:
    #   test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    networks:
      - vapor-network

networks:
  vapor-network:
    driver: bridge
